spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5Dialect"
  database:
    driverClassName: "com.mysql.jdbc.Driver"
  datasource:
    url: "jdbc:mysql://localhost:3306/itemsharingdatabase"
    username: "root"
    password: "{cipher}8a588fb72b18ceeb100d2b6c96d297ef1baabe223f6cac339d13a0d3ddc7ebd3"
    testWhileIdle: "true"
    validationQuery: "SELECT 1"

server:
  port: 8082

eureka:
  instance:
    perferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/